services:
  unit3d:
    image: unit3d:latest
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./UNIT3D:/var/www/html
      - ./unit3d.conf:/etc/nginx/conf.d/unit3d.conf
    env_file:
      - .env
    entrypoint: /entrypoint.sh

  unit3d-setup:
    image: unit3d:latest
    volumes:
      - ./UNIT3D:/var/www/html
    env_file:
      - .env
    entrypoint: /entrypoint.sh setup

  unit3d-debug:
    image: unit3d:latest
    volumes:
      - ./UNIT3D:/var/www/html
    env_file:
      - .env
    entrypoint: /entrypoint.sh debug