version: '3.8'

services:
  unit3d:
    image: unit3d:latest
    container_name: unit3d
    env_file:
      - env
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "6379:6379"
    command: tail -f /dev/null